# NumPy

NumPy is the fundamental package for scientific computing with Python. It contains among other things:

- a powerful N-dimensional array object
- sophisticated (broadcasting) functions
- tools for integrating C/C++ and Fortran code
- useful linear algebra, Fourier transform, and random number capabilities

Besides its obvious scientific uses, NumPy can also be used as an efficient multi-dimensional container of generic data. Arbitrary data-types can be defined. This allows NumPy to seamlessly and speedily integrate with a wide variety of databases.

Library documentation: <a>http://www.numpy.org/</a>

In [2]:
import numpy as np

In [3]:
# declare a vector using a list as the argument
v = np.array([1,2,3,4])
v

array([1, 2, 3, 4])

In [4]:
# declare a matrix using a nested list as the argument
M = np.array([[1,2],[3,4]])
M

array([[1, 2],
       [3, 4]])

In [5]:
# still the same core type with different shapes
type(v), type(M)

(numpy.ndarray, numpy.ndarray)

In [6]:
M.size

4

In [7]:
# arguments: start, stop, step
x = np.arange(0, 10, 1)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
np.linspace(0, 10, 25)

array([ 0.        ,  0.41666667,  0.83333333,  1.25      ,  1.66666667,
        2.08333333,  2.5       ,  2.91666667,  3.33333333,  3.75      ,
        4.16666667,  4.58333333,  5.        ,  5.41666667,  5.83333333,
        6.25      ,  6.66666667,  7.08333333,  7.5       ,  7.91666667,
        8.33333333,  8.75      ,  9.16666667,  9.58333333, 10.        ])

In [9]:
np.logspace(0, 10, 10, base=10)

array([1.00000000e+00, 1.29154967e+01, 1.66810054e+02, 2.15443469e+03,
       2.78255940e+04, 3.59381366e+05, 4.64158883e+06, 5.99484250e+07,
       7.74263683e+08, 1.00000000e+10])

In [10]:
x, y = np.mgrid[0:5, 0:5]
x

array([[0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1],
       [2, 2, 2, 2, 2],
       [3, 3, 3, 3, 3],
       [4, 4, 4, 4, 4]])

In [11]:
y

array([[0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4],
       [0, 1, 2, 3, 4]])

In [12]:
from numpy import random

In [13]:
np.random.rand(5,5)

array([[0.04505867, 0.23823358, 0.15970799, 0.83624123, 0.4636515 ],
       [0.83731894, 0.63243193, 0.17381338, 0.89957534, 0.07819936],
       [0.02453495, 0.72839618, 0.96781697, 0.35193279, 0.33090975],
       [0.08884297, 0.87777649, 0.9334177 , 0.17896014, 0.67067486],
       [0.60341922, 0.44176256, 0.77209384, 0.86240024, 0.0637913 ]])

In [14]:
# normal distribution
random.randn(5,5)

array([[-0.66346423, -0.95603101,  1.09934955,  0.39780572,  1.07888412],
       [-1.02239086, -1.1904147 ,  0.18106995, -1.57383995, -1.24191744],
       [ 0.27848763,  0.60904495,  0.28700071, -0.5385085 , -0.57206245],
       [ 1.25649998, -0.73510132,  0.0140068 , -0.2515755 ,  0.52830908],
       [ 0.04301147,  0.66837471,  1.19693082, -1.18550052,  0.66644466]])

In [15]:
diag([1,2,3])

NameError: name 'diag' is not defined

In [16]:
M.itemsize

4

In [17]:
M.nbytes

16

In [18]:
M.ndim

2

In [19]:
v[0], M[1,1]

(1, 4)

In [20]:
M[1]

array([3, 4])

In [21]:
# assign new value
M[0,0] = 7
M

array([[7, 2],
       [3, 4]])

In [22]:
M[0,:] = 0
M

array([[0, 0],
       [3, 4]])

In [26]:
# slicing works just like with lists
A = np.array([1,2,3,4,5])
A[1:3]

array([2, 3])

In [27]:
A = np.array([[n+m*10 for n in range(5)] for m in range(5)])
A

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [28]:
row_indices = [1, 2, 3]
A[row_indices]

array([[10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34]])

In [29]:
# index masking
B = np.array([n for n in range(5)])
row_mask = np.array([True, False, True, False, False])
B[row_mask]

array([0, 2])

### Linear Algebra

In [30]:
v1 = np.arange(0, 5)

In [31]:
v1 + 2

array([2, 3, 4, 5, 6])

In [32]:
v1 * 2

array([0, 2, 4, 6, 8])

In [33]:
v1 * v1

array([ 0,  1,  4,  9, 16])

In [34]:
dot(v1, v1)

NameError: name 'dot' is not defined

In [31]:
dot(A, v1)

array([ 30, 130, 230, 330, 430])

In [35]:
# cast changes behavior of + - * etc. to use matrix algebra
M = np.matrix(A)
M * M

matrix([[ 300,  310,  320,  330,  340],
        [1300, 1360, 1420, 1480, 1540],
        [2300, 2410, 2520, 2630, 2740],
        [3300, 3460, 3620, 3780, 3940],
        [4300, 4510, 4720, 4930, 5140]])

In [36]:
# inner product
v.T * v

array([ 1,  4,  9, 16])

In [37]:
C = np.matrix([[1j, 2j], [3j, 4j]])
C

matrix([[0.+1.j, 0.+2.j],
        [0.+3.j, 0.+4.j]])

In [38]:
np.conjugate(C)

matrix([[0.-1.j, 0.-2.j],
        [0.-3.j, 0.-4.j]])

In [39]:
# inverse
C.I

matrix([[0.+2.j , 0.-1.j ],
        [0.-1.5j, 0.+0.5j]])

### Statistics

In [41]:
np.mean(A[:,3])

23.0

In [43]:
np.std(A[:,3]), np.var(A[:,3])

(14.142135623730951, 200.0)

In [44]:
A[:,3].min(), A[:,3].max()

(3, 43)

In [47]:
d = np.arange(1, 10)
np.sum(d), np.prod(d)

(45, 362880)

In [48]:
np.cumsum(d)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45], dtype=int32)

In [49]:
np.cumprod(d)

array([     1,      2,      6,     24,    120,    720,   5040,  40320,
       362880], dtype=int32)

In [50]:
# sum of diagonal
np.trace(A)

110

In [51]:
m = np.random.rand(3, 3)
m

array([[0.06033701, 0.52846295, 0.41601341],
       [0.62251048, 0.21328349, 0.11804607],
       [0.26191734, 0.67872494, 0.56396019]])

In [52]:
# use axis parameter to specify how function behaves
m.max(), m.max(axis=0)

(0.6787249444413987, array([0.62251048, 0.67872494, 0.56396019]))

In [53]:
A

array([[ 0,  1,  2,  3,  4],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [54]:
# reshape without copying underlying data
n, m = A.shape
B = A.reshape((1,n*m))

B

array([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14, 20, 21, 22, 23, 24, 30,
        31, 32, 33, 34, 40, 41, 42, 43, 44]])

In [55]:
# modify the array
B[0,0:5] = 5
B

array([[ 5,  5,  5,  5,  5, 10, 11, 12, 13, 14, 20, 21, 22, 23, 24, 30,
        31, 32, 33, 34, 40, 41, 42, 43, 44]])

In [56]:
# also changed
A

array([[ 5,  5,  5,  5,  5],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])

In [57]:
# creates a copy
B = A.flatten()
B

array([ 5,  5,  5,  5,  5, 10, 11, 12, 13, 14, 20, 21, 22, 23, 24, 30, 31,
       32, 33, 34, 40, 41, 42, 43, 44])

In [60]:
# can insert a dimension in an array
v = np.array([1,2,3])
v[:, np.newaxis], v[:, np.newaxis].shape, v[np.newaxis,:].shape

(array([[1],
        [2],
        [3]]),
 (3, 1),
 (1, 3))

In [61]:
np.repeat(v, 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [62]:
np.tile(v, 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [63]:
w = np.array([5, 6])

In [64]:
np.concatenate((v, w), axis=0)

array([1, 2, 3, 5, 6])

In [67]:
# deep copy
B = np.copy(A)
B

array([[ 5,  5,  5,  5,  5],
       [10, 11, 12, 13, 14],
       [20, 21, 22, 23, 24],
       [30, 31, 32, 33, 34],
       [40, 41, 42, 43, 44]])